package:
  name: gmp
  version: 6.1.2

source:
  sha256: 5275bb04f4863a13516b2f39392ac5e272f5e1bb8057b18aec1c9b79d73d8fb2
  url: https://gmplib.org/download/gmp/gmp-6.1.2.tar.bz2
build:
  library: true
  script: |
    emconfigure ./configure CFLAGS="-fPIC" --disable-assembly --host none --enable-cxx
    emmake make -j ${PYODIDE_JOBS:-3}
