package:
  name: tinydb
  version: 4.7.0
source:
  url: https://files.pythonhosted.org/packages/2c/76/93df2ac94dacc0f63e4263ee7cf4787d0c3df22859d9e0627958048f39c7/tinydb-4.7.0-py3-none-any.whl
  sha256: e2cdf6e2dad49813e9b5fceb3c7943387309a8738125fbff0b58d248a033f7a9
test:
  imports:
    - tinydb
about:
  home: https://github.com/msiemens/tinydb
  PyPI: https://pypi.org/project/tinydb
  summary:
    TinyDB is a tiny, document oriented database optimized for your happiness
    :)
  license: MIT
