package:
  name: pycalphad
  version: 0.10.1
source:
  sha256: 8325a327280d971b366da0c6c4bee88ade4b35aa07fccc028381f7c543535e9a
  url: https://files.pythonhosted.org/packages/68/08/f29c25d2e33611464ff819acf13b285a570fdc86ccece237d752e4780db8/pycalphad-0.10.1.tar.gz
build:
  ldflags: |
    -L$(NUMPY_LIB)
requirements:
  run:
    - matplotlib
    - numpy
    - pyparsing
    - pytest
    - scipy
    - symengine
    - tinydb
    - xarray
test:
  imports:
    - pycalphad
