package:
  name: libsymengine
  version: 0.9.0
source:
  sha256: dcf174ac708ed2acea46691f6e78b9eb946d8a2ba62f75e87cf3bf4f0d651724
  url: https://github.com/symengine/symengine/releases/download/v0.9.0/symengine-0.9.0.tar.gz
build:
  library: true
  script: |
      emcmake cmake \
        -DBUILD_TESTS=OFF \
        -DBUILD_BENCHMARKS=OFF \
        -DINTEGER_CLASS=gmp \
        -DCMAKE_PREFIX_PATH=$PYODIDE_ROOT/packages/symengine/dist \
        -DCMAKE_INSTALL_PREFIX=$PYODIDE_ROOT/packages/symengine/dist \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DBUILD_FOR_DISTRIBUTION=yes \
        -DBUILD_SHARED_LIBS=no \
        -DGMP_LIBRARY=$PYODIDE_ROOT/packages/gmp/build/gmp-6.1.2/.libs/libgmp.a \
        -DGMP_INCLUDE_DIR=$PYODIDE_ROOT/packages/gmp/build/gmp-6.1.2 \
        .
      emmake make install
requirements:
  run:
    - gmp