name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-core:
    runs-on: ubuntu-latest
    container:
      image: pyodide/pyodide:0.20.0
      options: --cpus 1
    steps:
      - uses: actions/checkout@v2
        with:
          path: _overlay
      - run: cp -r _overlay/* /src/pyodide/packages/
      - run: echo "Hello World"

