name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-core:
    runs-on: ubuntu-latest
    container:
      image: pyodide/pyodide:0.20.0
      options: --cpus 1
      env:
        PYODIDE_ROOT: /src/pyodide/
    steps:
      - uses: actions/checkout@v2
        with:
          path: _overlay
      - run: cp -r _overlay/packages/* /src/pyodide/packages/
      - run: mkdir -p /src/pyodide/dist
      - run: python -m pip install /src/pyodide/pyodide-build/.
      - run: python -m pyodide_build buildpkg /src/pyodide/packages/pycalphad/meta.yaml
      - run: python -m pyodide_build buildpkg /src/pyodide/packages/gmp/meta.yaml
      - run: python -m pyodide_build buildpkg /src/pyodide/packages/libsymengine/meta.yaml
      - run: python -m pyodide_build buildpkg /src/pyodide/packages/symengine/meta.yaml
      - run: python -m pyodide_build buildall --only 'pycalphad' /src/pyodide/packages /src/pyodide/dist
      - uses: actions/upload-artifact@v3
        with:
          name: pycalphad-wasm-wheel
          path: /src/pyodide/packages/pycalphad/dist/*.whl
      - uses: actions/upload-artifact@v3
        with:
          name: symengine-wasm-wheel
          path: /src/pyodide/packages/symengine/dist/*.whl
      - uses: actions/upload-artifact@v3
        with:
          name: pyodide-dist
          path: /src/pyodide/dist
